manager-dependencies:
- IPython
- Send2Trash
- anyio
- arrow
- asttokens
- attr
- attrs
- babel
- cffi
- charset_normalizer
- cloudpickle
- colorama
- comm
- conda_pack
- dateutil
- debugpy
- executing
- fastjsonschema
- floability
- fqdn
- httpx
- idna
- ipykernel
- ipython
- ipython_pygments_lexers
- isoduration
- jedi
- jinja2
- json5
- jsonschema
- jsonschema_specifications
- jupyter_client
- jupyter_console
- jupyter_core
- jupyter_events
- jupyter_lsp
- jupyter_server
- jupyterlab
- markdown_it_py
- matplotlib_inline
- nbclient
- nbconvert
- nbformat
- ndcctools
- notebook
- numpy
- packaging
- parso
- pip
- platformdirs
- prompt_toolkit
- psutil
- pure_eval
- pygments
- pytest
- referencing
- rich
- rpds
- setuptools-78.1.0
- stack_data
- tornado
- tqdm
- traitlets
- uri_template
- wcwidth
- webcolors
- websocket_client
- zmq
worker-dependencies:
- cloudpickle
- numpy
