manager-dependencies:
- Babel
- Cartopy
- Cython
- IPython
- Markdown
- PIL
- QtPy
- accessible_pygments
- alabaster
- astropy
- asttokens
- attr
- awkward
- awkward_cpp
- boost_histogram
- cachetools
- charset_normalizer
- cloudpickle
- cmake
- coffea
- comm
- conda_pack
- correctionlib
- cycler
- dask
- dask_awkward
- dask_awkward_sizeof
- dask_histogram
- dask_histogram_sizeof
- dateutil
- debugpy
- distributed
- docutils
- executing
- fiona
- fonttools
- fsspec
- fsspec_xrootd
- hist
- histoprint
- humanfriendly
- importlib_metadata
- ipykernel
- ipympl
- ipython
- ipython_pygments_lexers
- ipywidgets
- jedi
- jsonschema
- jupyter_client
- jupyter_core
- kiwisolver
- llvmlite
- lz4
- markdown_it_py
- matplotlib
- matplotlib_inline
- mpl_toolkits
- mplhep
- mplhep_data
- myst_parser
- nbformat
- ndcctools
- netCDF4
- numba
- numpy
- numpydoc
- packaging
- pandas
- parso
- pip
- platformdirs
- proj
- prompt_toolkit
- psutil
- pure_eval
- pyarrow
- pydata_sphinx_theme
- pygments
- pyparsing
- pyproj
- pytest
- pytz
- qtconsole
- rasterio
- rich
- scipy
- setuptools-78.1.0
- sphinx
- stack_data
- tabulate
- tlz
- toolz
- tornado
- tqdm
- traitlets
- uhi
- uproot
- vector
- versioneer
- wcwidth
- wheel
- xarray
- xxhash
- yaml
- zipp
- zmq
worker-dependencies:
- attr
- awkward
- awkward_cpp
- boost_histogram
- cachetools
- charset_normalizer
- cloudpickle
- coffea
- conda_pack
- correctionlib
- dask
- dask_awkward
- dask_awkward_sizeof
- dask_histogram
- dask_histogram_sizeof
- dateutil
- debugpy
- fonttools
- fsspec
- fsspec_xrootd
- hist
- histoprint
- importlib_metadata
- ipython
- ipython_pygments_lexers
- jsonschema
- jupyter_client
- jupyter_core
- llvmlite
- lz4
- markdown_it_py
- matplotlib_inline
- nbformat
- ndcctools
- numba
- numpy
- packaging
- pandas
- pip
- psutil
- pyarrow
- pygments
- pytz
- rich
- scipy
- setuptools-78.1.0
- tlz
- toolz
- tqdm
- uhi
- uproot
- vector
- wheel
- xxhash
- yaml
- zipp
