manager-dependencies:
- Babel
- Cartopy
- Cython
- IPython
- Markdown
- QtPy
- accessible_pygments
- alabaster
- astropy
- asttokens
- attr
- awkward
- awkward_cpp
- bokeh
- boost_histogram
- cachetools
- cffi
- chardet
- cloudpickle
- cmake
- coffea
- colorama
- comm
- conda_pack
- correctionlib
- cytoolz
- dask
- dask_awkward
- dask_histogram
- dateutil
- debugpy
- distributed
- docutils
- executing
- fastjet
- fiona
- fonttools
- fsspec
- hist
- histoprint
- humanfriendly
- ipykernel
- ipympl
- ipython
- ipython_pygments_lexers
- jedi
- jinja2
- jsonschema
- jupyter_client
- jupyter_core
- llvmlite
- lz4
- markdown_it_py
- markupsafe
- matplotlib_inline
- myst_parser
- nbformat
- ndcctools
- netCDF4
- numba
- numpy
- numpydoc
- packaging
- pandas
- parso
- pip
- platformdirs
- proj
- prompt_toolkit
- psutil
- pure_eval
- pyarrow
- pycparser
- pydata_sphinx_theme
- pygments
- pyproj
- pytest
- pytest_metadata
- pytz
- qtconsole
- rasterio
- rich
- scipy
- setuptools-78.1.0
- sphinx
- stack_data
- tabulate
- tblib
- tlz
- toolz
- tornado
- tox
- tqdm
- traitlets
- uhi
- uproot
- vector
- versioneer
- wcwidth
- wheel
- xarray
- xxhash
- yaml
- zmq
- zstandard
worker-dependencies:
- attr
- awkward
- awkward_cpp
- bokeh
- boost_histogram
- cachetools
- cffi
- chardet
- cloudpickle
- coffea
- colorama
- conda_pack
- correctionlib
- cytoolz
- dask
- dask_awkward
- dask_histogram
- dateutil
- debugpy
- distributed
- fastjet
- fonttools
- fsspec
- hist
- histoprint
- ipython
- ipython_pygments_lexers
- jinja2
- jsonschema
- jupyter_client
- jupyter_core
- llvmlite
- lz4
- markdown_it_py
- markupsafe
- matplotlib_inline
- nbformat
- ndcctools
- numba
- numpy
- packaging
- pandas
- pip
- psutil
- pyarrow
- pycparser
- pygments
- pytest
- pytest_metadata
- pytz
- rich
- scipy
- setuptools-78.1.0
- tblib
- tlz
- toolz
- tox
- tqdm
- uhi
- uproot
- vector
- wheel
- xxhash
- yaml
- zstandard
